<?php

/**
 *  This is a base compile file provided by Laravel
 *
 * @name       compile
 * @category   Configuration
 * @package    Configuration
 * @author     Ajay Bhosale <ajay.bhosale@silicus.com>
 * @license    Silicus http://www.silicus.com/
 * @version    GIT: $Id$
 * @link       None
 * @filesource
 */
return [

    /*
      |--------------------------------------------------------------------------
      | Additional Compiled Classes
      |--------------------------------------------------------------------------
      |
      | Here you may specify additional classes to include in the compiled file
      | generated by the `artisan optimize` command. These should be classes
      | that are included on basically every request into the application.
      |
     */

    'files' => [
    //
    ],
    /*
      |--------------------------------------------------------------------------
      | Compiled File Providers
      |--------------------------------------------------------------------------
      |
      | Here you may list service providers which define a "compiles" function
      | that returns additional files that should be compiled, providing an
      | easy way to get common files from any packages you are utilizing.
      |
     */
    'providers' => [
    //
    ],
];
